---
- name : Dry Run puppet
  hosts: Web
  become: yes
  become_method: sudo
  serial: 1
 # vars_files:
 #   - /password.yaml

  tasks:
  - name: Handle the error
    block:
     - debug:
         msg: 'I execute normally'
     - include_tasks: logfile.yml
       vars:
         logfilepath: "/tmp/puppet_dryrun"

     - name: "Start puppet agent for Dry Run"
       shell: /opt/puppetlabs/bin/puppet agent --test --verbose --detailed-exitcodes  --logdest /tmp/puppet_dryrun --noop
       register: puppet_agent
       changed_when: puppet_agent.rc == 2
       failed_when: puppet_agent.rc != 2 and puppet_agent.rc != 0
    rescue:
     - debug:
         msg: 'I caught an error, can do stuff here to fix it'
     - debug:
         msg: 'check /tmp/puppet_dryrun for more information'
