---
- name : Dry Run Puppet
  hosts: Web
  become: yes
  become_method: sudo
  gather_facts: no
 # strategy: free
  ignore_unreachable: True
  serial: 8
 # vars_files:
 #   - /password.yaml

  tasks:

  - include_tasks: logfile.yml
    vars:
      logfilepath: "/tmp/puppet_dryrun"

  - name: "Start puppet agent for Dry Run"
    shell: /opt/puppetlabs/bin/puppet agent --test --verbose --detailed-exitcodes  --logdest /tmp/puppet_dryrun --noop
    async: 1000  # Maximum runtime in seconds. Adjust as needed.
    poll: 0 # Fire and continue (never poll)
    register: puppet_agent
    #changed_when: puppet_agent.rc == 2
    #failed_when: puppet_agent.rc != 2 and puppet_agent.rc != 0
    ignore_errors: True
  - name: 'Puppet - check on async task'
    async_status:
      jid: "{{ puppet_agent.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    delay: 60  # Check every 5 seconds. Adjust as you like.
    retries: 30 # Retry up to 30 times. Adjust as needed.

  #- name: "Puppet Dry Run Output"
  #  debug: var=puppet_agent.stdout_lines
  #  when: "'FAILED' in puppet_agent.stderr"
 # - name: fail the play if the previous command did not succeed on a particular VM.
  #  fail: msg="the Puppet dry run failed on this node please check log file /tmp/puppet_dryrun"
  #  when: "puppet_agent.rc != 0"
