---
- name : Creating file for test Ansible execution 
  hosts: all
  become: yes
  #become_method: sudo
  gather_facts: no
  #strategy: free
  #ignore_unreachable: True
  max_fail_percentage: 30
  serial: 8
 # vars_files:
 #   - /password.yaml

  tasks:

 # - include_tasks: file.yml
  #  vars:
   #   logfilepath: "/tmp/test.txt"
   # create a new file on each host
  - copy: 
     content: "file creation test speed" 
     dest: "/tmp/test.txt"
     backup: yes
   # owner: root
   # group: root
     mode: 0644
